name: Validate Pr
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 7 for ant
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '7'
      - name: Setup Ruby 2.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.3
      - name: Install Compass
        run: gem install compass
      - run: ant setupDB test dist
