name: Validate Pr
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gem install compass
      - run: ant setupDB test dist
